### ISSUE TITLE
[Proposal, 제안] 안녕하세요, 개발자님. 

### ISSUE THREAD

**Issue by faker007** [jyp-on/Wanted-Memory#2]
# 제안
* 원티드 채용 공고에서, 이 채용 공고는 더 이상 보이지 않게 하기 기능.

# Workflow
## AS-IS
* 현재는 채용 공고를 확인 하면, 마킹만 됨.

## TO-BE
* 채용 공고 내에서 이 채용 공고는 보이지 않게 할래요 버튼 추가.
* 크롬 플러그인 내에서 보이지 않게 할래요를 리스트로 디스플레이 및 삭제 기능.

# 마무리
* 만들어 주셔서 감사합니다. 굿... 👍

**Comment by jyp-on** [comment]
반영하였습니다!
